language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - py.test --cov-report term --cov=bireus tests/

after_success:
  - coveralls