language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update
  - pip install coveralls

install:
  - pip install -r requirements.txt

script:
  - pytest tests

after_success:
  - coveralls